### ISSUE TITLE
无法找到363217565.debug.open.weixin.qq.com的DNS地址

### ISSUE THREAD

**Issue by tardis103** [zce/weapp-demo#10]
初次调试运行显示
无法找到363217565.debug.open.weixin.qq.com的DNS地址

**Comment by zce** [comment]
确保正确安装了微信Web开发者工具，并关闭代理

**Comment by tardis103** [comment]
安装应该没问题，  代理也关闭了
Request URL:http://1763377845.appservice.open.weixin.qq.com/appservice 一直请求失败

**Comment by zce** [comment]
新建一个`Quick Start`项目试试

**Comment by tardis103** [comment]
quick start都不行   显示不了
是要卸载重新装么

**Comment by zce** [comment]
对喽！

**Comment by tardis103** [comment]
就是代理问题！！   谢谢！！工具里面设置一下就好了

**Comment by liuke095** [comment]
我看传智得课表最近更新了，里有这个微信小程序这个项目，也是豆瓣的这个项目，那个课程也是你讲的嘛

**Comment by RaulSteven** [comment]
VM311:2 app.json
Expecting 'STRING','}', got INVALID
> 1 | {
    |  ^(anonymous function) @ VM311:2

这是什么错误？
