### ISSUE TITLE
下载了backup分支代码，用开发工具打开项目后为什么没有看到任何请求的资源？

### ISSUE THREAD

**Issue by BubbleStar** [zce/weapp-demo#12]

**Comment by BubbleStar** [comment]
问题补充：打开的微信页面只有title：电影<<豆瓣，其他区域一片空白

**Comment by zce** [comment]
https://github.com/zce/weapp-demo/commit/46b7abe947d235458612cde8018d24510040928e

**Comment by BubbleStar** [comment]
刚刚看到了解决方法：
请求时header需要是这种形式
header:{
        "Content-Type":"json"
 },

**Comment by zce** [comment]
已经更新
