### ISSUE TITLE
怎么打开呀,刚接触,哈哈

### ISSUE THREAD

**Issue by GodRiWin** [zce/weapp-demo#2]
怎么打开呀,刚接触,哈哈

**Comment by zce** [comment]
- 安装`微信Web开发者工具`
- 用开发者工具打开
- 可以看看下面的README

**Comment by zce** [comment]
ping @GodRiWin

**Comment by ontheway1215** [comment]
Expecting 'STRING','}', got INVALID
> 1 | {
    |  ^
打开项目报这个错是什么原因呢？
