### ISSUE TITLE
调用豆瓣api接口提示下面错误，怎么解决

### ISSUE THREAD

**Issue by wukchao** [zce/weapp-demo#22]
asdebug.js:1 GET https://api.douban.com/v2/movie/coming_soon?start=0&count=3 400 (Bad Request)

**Comment by zce** [comment]
这种情况有很多原因，最常见的就是 IP 限制（豆瓣官方对免费的 API 限制了同一 IP 同一时间段的请求次数），还有可能是请求 header 中 `Content-Type` 设置有问题，正确设置参考：https://github.com/zce/weapp-demo/blob/master/src/utils/fetch.js#L16

**Comment by wukchao** [comment]
我使用postman可以获取到数据，应该不是IP限制，但是运行示例小程序就报那个错误，请求 header 中 Content-Type 设置没有问题

**Comment by wukchao** [comment]
header: { 'Content-Type': 'application/json' },将这个改为header: { 'Content-Type': 'json' }, 就可以了

**Comment by zce** [comment]
好的，那我关闭了
