### ISSUE TITLE
 master 分支上app.json报错

### ISSUE THREAD

**Issue by zhaocongdong** [zce/weapp-demo#24]
parse json 错误
VM250:2 app.json
Expecting 'STRING','}', got INVALID
> 1 | {
    |  ^
(anonymous) @ VM250:2

**Comment by caoshuaitong** [comment]
@zhaocongdong  因为json文件中不能有注释，作者为了注释清晰内部加了注释，要删除所有json文件的注释才行

**Comment by zhaocongdong** [comment]
@caoshuaitong 对的.json 里面是不能有注释,好几个文件里面都需要删掉注释.

**Comment by zce** [comment]
仔细看清楚 README， `src` 目录中的文件会经过转换然后输出到 `dist` 目录，转换过程会自动去除注释
