### ISSUE TITLE
npm run build 生成的生产环境的代码无法触发form的submit事件

### ISSUE THREAD

**Issue by leamiko** [zce/weapp-demo#28]
npm run build 生成的生产环境的代码无法触发form的submit事件
```
<form bindsubmit="xx">
...
<button class="weui-btn" type="primary" formType="submit">确定</button>			
...
</form>
```
不知道gulpfile.js中的uglify这段，是不是要加点什么进行过滤
```
.pipe(plugins.if(isProduction, plugins.uglify())) 
```

**Comment by leamiko** [comment]
经过排查发现是gulp-htmlmin的问题
生成环境下`formType`被转成了`formtype`
加`caseSensitive`: Treat attributes in case sensitive manner (useful for custom HTML tags)
htmlmin的option加一个 caseSensitive:true问题就解决了默认这个属性为false

希望@zce 修复下 谢谢

**Comment by zce** [comment]
@leamiko 
thanks
