### ISSUE TITLE
在微信开发工具里预览上传代码包超限问题

### ISSUE THREAD

**Issue by stingbo** [zce/weapp-demo#29]
在工具里调试都没有问题，但在预览上传代码时提示:`代码包大小为 3021 kb，超出限制 1997 kb，请删除文件后重试`，请问这个问题怎么解决呢？谢谢

**Comment by zce** [comment]
小程序要求最终上传的程序包大小不允许超过1024KB（而开发工具没有限制）
劳驾仔细看看小程序的文档
