### ISSUE TITLE
https://api.map.baidu.com 不在以下 request 合法域名

### ISSUE THREAD

**Issue by zhaipanyu** [zce/weapp-demo#36]
![image](https://user-images.githubusercontent.com/11550755/34238522-0d875af4-e63d-11e7-9444-a693dd43441b.png)
npm  run dev后生成的dist文件, 用微信开发者工具打开dist就报错:https://api.map.baidu.com 不在以下 request 合法域名,为什么报错文档没相关说明,请问怎么解决?

**Comment by zhaipanyu** [comment]
使用的是最新的微信开发者工具.

**Comment by zhaipanyu** [comment]
解决了,默认不勾选,自己勾选上
![image](https://user-images.githubusercontent.com/11550755/34238772-79a9e818-e63e-11e7-9535-709b8f16445a.png)

**Comment by zce** [comment]
@zhaipanyu 治标的方法是在微信管理平台中将你需要发起请求的地址加入到白名单，这样才可以真机调试或者上线

**Comment by zhaipanyu** [comment]
thanks
