### ISSUE TITLE
访问豆瓣api出现403

### ISSUE THREAD

**Issue by flyfox11** [zce/weapp-demo#37]
![image](https://user-images.githubusercontent.com/23090200/35133084-466e8f6c-fd09-11e7-8562-da6396a877ae.png)
但是在浏览器访问这个接口是没问题的，卡到这两天了，网上各种搜都没找到解决方案，紧急！！！

**Comment by zhiqin520** [comment]
同上, 而且之前是可以的 ,就这两天不可以了

**Comment by zce** [comment]
豆瓣官方的限制，现已规避，具体请看 README
