### ISSUE TITLE
闪屏bug

### ISSUE THREAD

**Issue by jintangWang** [zce/weapp-demo#41]
![bug](https://user-images.githubusercontent.com/12557847/36708394-c68886d6-1bad-11e8-9923-9bbe0bd163ee.gif)
点击电影详情，先闪屏到 "我的"，然后再进入详情

**Comment by zce** [comment]
@jintangWang 请真机测试，模拟器可能有问题

**Comment by jintangWang** [comment]
@zce 我用真机打开时白屏，是不是因为tls版本的原因？

**Comment by zce** [comment]
修改的 APPID 的白名单过后再模拟器上需要重启过后才会生效

**Comment by jintangWang** [comment]
@zce 谢谢啊，重启后好了
