### ISSUE TITLE
请问反向代理如何实现的？

### ISSUE THREAD

**Issue by jintangWang** [zce/weapp-demo#42]
我在本地搭建了个nginx，可以实现http的反向代理，但是豆瓣的api：https://api.douban.com 是https的，请问怎么咋实现了，查了好多了，还是不得其法

**Comment by zce** [comment]
HTTPS 与反向代理没有任何关系，你可以自己去购买 SSL 证书

**Comment by jintangWang** [comment]
我用openssl自己生成了一个自签名ssl证书，可以访问本地`https://localhost`，但如何实现接口转发呢？
