### ISSUE TITLE
本来接口是能访问的，但过几十分钟接口就报400了

### ISSUE THREAD

**Issue by bibibabibo** [zce/weapp-demo#43]
前辈您好。萌新使用您的https://douban.uieee.com ，开始是好的 ， 但过会儿接口就报400，然后过个20来分钟就又能请求了。望指点是什么问题呢？蟹蟹 
data : {msg: "rate_limit_exceeded2: 47.93.58.139", code: 112, request: "GET /v2/movie/****"}

**Comment by zce** [comment]
因为有很多人都在使用我搭建的这个反向代理（相同IP），豆瓣源接口对于同一个 IP 在同一个时间段的请求是有限制的，所以出现这种情况，属于正常
