### ISSUE TITLE
豆瓣请求 400 bad Request

### ISSUE THREAD

**Issue by yukunqi** [zce/weapp-demo#47]
{"msg":"Invalid request","code":999,"request":"GET \/v2\/isbn\/9787508662091"}

你好 我使用你的接口去请求 但是你的网址为什么我在小程序上面 关掉了域名检测 会报这个错误

用chrome浏览器直接请求就不会。请问原因是？

**Comment by yukunqi** [comment]
发现了问题的原因了，原因就是在小程序的wx.request里面默认的header的请求头中会带content-type application/json  发送过去之后 可能作者的服务器那边没有解析到参数导致400 。 我把content-type 改成空格就可以正常请求了。

**Comment by zce** [comment]
你这是说的什么呀？能不能把话说清楚了~

**Comment by yukunqi** [comment]
我说的意思是直接使用这个接口在小程序上请求会报错，需要修改header。

**Comment by zce** [comment]
👌我是看你的第一个 comment，确实没看懂~
给个建议：以后能不能写完过后自己看一遍，看看能不能看清，有没有描述清楚。

**Comment by yukunqi** [comment]
明白
